### ISSUE TITLE
I'd like to use crypto only trading pairs

### ISSUE THREAD

**Issue by philippeowagner** [mcardillo55/gdax-trader#3]
.. like BTC/LTC  or BTC/ETH. This would have an effect on `round_fiat` and `round_coin`. 

Any thoughts on that one?

**Comment by mcardillo55** [comment]
I'm not sure I'm seeing the effect on `round_fiat`/`round_coin`. I could see some of the logic in `determine_trades` needing to be modified, but at this point I kind of expect that users will modify that to their own needs anyway.
