### ISSUE TITLE
Market order vs Limit

### ISSUE THREAD

**Issue by yamat124** [mcardillo55/gdax-trader#6]
I just have a quick question. why did you decide to make the bot trade with market instead of limit? Every market order has a fee most limit orders have no fee. is better to pay the fee?

**Comment by mcardillo55** [comment]
It starts by trying limit orders, then if the price slips past max_slippage (set in config), it will do a market order. I was noticing a few times where the price slipped way past the amount of fees and decided to add this option. It's a relatively new change, and I'm planning on adding the option to disable it. If you want to disable market orders for now, just set max_slippage to something very high that it'll never reach.
