### ISSUE TITLE
30m period for BTC not working

### ISSUE THREAD

**Issue by linuxster** [mcardillo55/gdax-trader#7]
Hi,
I cannot get the 30m setting to work for BTC. 60m appears working.

**Comment by mcardillo55** [comment]
[GDAX recently limited their supported granularities to one minute, five minutes, fifteen minutes, one hour, six hours, or one day.](https://docs.gdax.com/#get-historic-rates) I should probably update the README to reflect that. I've personally been collecting my own historical data and using that for now, but I don't think it's good enough for the public to use. If you want to set up your own mirror though, [check out the project.](https://github.com/mcardillo55/gdax-mirror)

**Comment by linuxster** [comment]
ok thanks I will take a look. are you then connecting to your mongodb instance and streaming into the get_historical_data logic?

**Comment by mcardillo55** [comment]
I serve the data via a flask microservice that connects to the mongodb in app.py, trying to mimic the response from the official GDAX api.
